#
# Environment variables for configuring the stack
# are prefixed with OPS_ (stands for OpenPypeStack).
#
# Variables for OpenPype server backend are prefixed
# with OPENPYPE
#

version: "3.3"
services:
  postgres:
    image: postgres
    ports:
      - "${OPS_PG_LISTEN-127.0.0.1:54321}:5432"
    environment:
      - "POSTGRES_USER=pypeusr"
      - "POSTGRES_PASSWORD=pypepass"
      - "POSTGRES_DB=pype"
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped
      #    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]


  redis:
    image: redis:alpine
    expose:
      - "6379"
    restart: unless-stopped

  backend:
    build: "./openpype4-backend"
    volumes:
        - "./openpype4-backend:/openpype"
    ports:
      - "${OPS_BACKEND_LISTEN-5000}:5000"
    working_dir: /openpype
    command: ./start.sh
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
    environment:
      - "OPENPYPE_DISCORD_CLIENT_ID=${OPENPYPE_DISCORD_CLIENT_ID-}"
      - "OPENPYPE_DISCORD_CLIENT_SECRET=${OPENPYPE_DISCORD_CLIENT_SECRET-}"
      - "OPENPYPE_GOOGLE_CLIENT_ID=${OPENPYPE_GOOGLE_CLIENT_ID-}"
      - "OPENPYPE_GOOGLE_CLIENT_SECRET=${OPENPYPE_GOOGLE_CLIENT_SECRET-}"

  caddy:
    image: caddy
    volumes:
      - "./support/Caddyfile:/etc/caddy/Caddyfile"
      - "./openpype4-frontend/dist:/frontend"
    ports:
      - "${OPS_HTTP_LISTEN-80}:80"
      - "${OPS_HTTPS_LISTEN-443}:443"
    environment:
      - "OPS_HOSTNAME=${OPS_HOSTNAME-*:80}"
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  db: {}
